//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JqueryDatatable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loading
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string city { get; set; }
        public string department { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
